default_platform(:android)

platform :android do
  desc "Build and upload a new release to the Play Store"
  lane :deploy do
    gradle(
      task: "bundle",
      build_type: "Release"
    )

    upload_to_play_store(
      track: "production",
      aab: "app/build/outputs/bundle/release/app.hypostats-release.aab",
      skip_upload_apk: true
    )
  end

  desc "Update metadata (screenshots, description) only"
  lane :update_metadata do
    upload_to_play_store(
      track: "production",
      skip_upload_aab: true,
      skip_upload_apk: true,
      skip_upload_changelogs: true
    )
  end
end
