name: Test

on:
  pull_request:
    branches: [ main ]

jobs:
  Test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    
    - name: Check formatting
      run: ./gradlew ktlintCheck

    - name: Run tests
      run: ./gradlew test
