name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Decode keystore
      env:
        ENCODED_KEYSTORE: ${{ secrets.KEYSTORE_BASE64 }}
      run: |
        base64 -d <<< "$ENCODED_KEYSTORE" > ${{ github.workspace }}/keystore.jks
    
    - name: Build Release APK
      run: ./gradlew assembleRelease
      env:
        ORG_GRADLE_PROJECT_KEYSTORE_FILE: ${{ github.workspace }}/keystore.jks
        ORG_GRADLE_PROJECT_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        ORG_GRADLE_PROJECT_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        ORG_GRADLE_PROJECT_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/app-release.apk
    
    - name: Create Release
      run: |
        gh release create ${{ github.ref_name }} \
          app/build/outputs/apk/release/app-release.apk \
          --title "HypoStats ${{ github.ref_name }}" \
          --generate-notes
      env:
        GH_TOKEN: ${{ github.token }}
